version: "3.8"

services:
    backend:
        image: ghcr.io/mysterioucz/wevis-datathon/backend:latest
        ports:
            - "3001:3001"
        environment:
            - PORT=3001
            - FRONTEND_URL=http://43.210.116.106
        restart: unless-stopped

    frontend:
        image: ghcr.io/mysterioucz/wevis-datathon/frontend:latest
        ports:
            - "80:80"
        environment:
            - PORT=80
            - HOSTNAME=0.0.0.0
        restart: unless-stopped
        depends_on:
            - backend
